# Generated by Django 3.1.4 on 2020-12-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_user_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_team',
            name='team_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
