# Generated by Django 3.1.4 on 2020-12-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_user_team_team_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='Player',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
        migrations.AlterModelTable(
            name='user_team',
            table='User_team',
        ),
    ]
