# Generated by Django 3.1.4 on 2020-12-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20201216_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='player_name',
        ),
    ]
