# Generated by Django 3.1.4 on 2020-12-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20201218_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('overall', models.IntegerField()),
                ('age', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('potential', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('classify', models.IntegerField()),
            ],
            options={
                'db_table': 'Pre_Player',
            },
        ),
    ]
